export const projects = [
  {
    title: 'My Personal Webpage (this website)',
    description: "My personal website made with React and Next framework. It uses a React Styled Components for app slyling.",
    image: '/images/project-4.jpg',
    tags: ['React', 'Next', 'Styled Component'],
    source: '/',
    visit: 'https://github.com/EdwardTymoshuk/my-personal-website',
    id: 0,
  },
  {
    title: 'Metaverse Website',
    description:"Modern React, Next.js 13 website with Framer Motion & Tailwind CSS.",
    image: '/images/project-2.jpg',
    tags: ['React', 'Next', 'Tailwind CSS', 'Framer Motion'],
    source: 'projects/metaversus-next-react-app',
    visit: 'https://github.com/EdwardTymoshuk/metaversus-next-react-app',
    id: 1,
  },
  {
    title: 'Admin Dashboard App',
    description: "A modern and fully responsive React admin dashboard page. It uses a Syncfusion (React UI components library) for building components and a Tailwind for styling. ",
      image: '/images/project-3.jpg',
      tags: ['React', 'Tailwind', 'Syncfusion'],
    source: 'projects/dashboard-syncfusion-app',
    visit: 'https://github.com/EdwardTymoshuk/admin-dashboard-react-app',
    id: 2,
  },
  {
    title: 'Bon Bon Francais',
  description: 'A landing page for online French teacher. Website is built with HTML5/CSS3/JS(ES6) and Bootstrap library. Website uses a simple REST API made with MongoDB and Express (also write by myself) for login/logout and feedback leaving and getting functions.',
      image: '/images/project-1.jpg',
      tags: ['HTML5', 'CSS3', 'JS', 'Bootstrap', 'MongoDB', 'Express'],
    source: '/projects/bonbonfrancais',
    visit: 'https://github.com/EdwardTymoshuk/Bonbonfrancais.online',
    id: 3,
  },
  {
    title: 'Snake Game',
    description: "My graduation project at Javascript course. It represents a simple game 'Snake' and is made with HTML5, CSS3 and Vanila Js. During this project I got a deeper knowledge of JS, wich helps me in my future projects.",
    image: '/images/project-5.jpg',
    tags: ['HTML5', 'CSS3', 'JS'],
    source: 'projects/snake',
    visit: 'https://github.com/EdwardTymoshuk/SnakeApp',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2014, text: 'Got a Bachelon degree in Mathematic with IT', },
  { year: 2015, text: 'Finished a postgraduate studies in "English in bussiness" field', },
  { year: 2018, text: 'Started learning HTML and CSS on my own, finished a couple online courses', },
  { year: 2019, text: 'Finished a JavaScript + React/Redux cours. Started making simple projects using learned technologies', },
  { year: 2021, text: 'Still studying and making projects. Got some basic knowledge of TypeScript, Node.js, MongoDB, Express', },
  { year: 2022, text: 'Developed my React skills (Hooks, Context API etc.), got acquainted SCSS and Tailwind tools. Started work as Web Developer at Crowbox company', },
];